name: Debian Build
description: Runs a `make` build in a Debian container with `g++`
inputs:
  build_number:
    description: Build number of the current workflow run.
    required: true
    default: 0
runs:
  using: docker
  image: Dockerfile
  args:
  - -D
  - BUILD_NUMBER=$INPUT_BUILD_NUMBER
  entrypoint: make
  
