name: Alpine Archive
description: Archives a directory in an Alpine container with `tar -czvf file -C dir .`
inputs:
  tar_gz_name:
    description: Name of archive file to create
    required: true
  file_or_dir_path:
    description: File or directory path to archive
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
  - '-czvf'
  - '${{ inputs.tar_gz_name }}'
  - '${{ inputs.file_or_dir_path }}'
  entrypoint: tar
