env:
  BUILD: ${{ github.run_number }}

name: 1.0.2+${{ BUILD }}

# manual and REST API runs only
on: workflow_dispatch

jobs:
  build:
    name: Build ./cpp (${{ github.run_number }})
    runs-on: ubuntu-latest
    
    steps:
    # checkout the latest source
    - name: Checkout
      uses: actions/checkout@v2

    # use a local action that builds a Debian container and runs `make` in it
    - name: Make ./cpp
      uses: ./.github/workflows/debian-build

    # run the app to make sure it was built
    - name: test ./cpp
      run: |
        echo ${{ github.workflow }}
        ./cpp

    # upload the artifact under the `hello-world` name
    - name: Upload ./cpp artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: hello-world
        path: ./cpp

  release:
    name: Create a draft release for ./cpp
    needs: build
    runs-on: ubuntu-latest

    steps:
    # create a draft GitHub release
    - name: Create a draft release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: v1.0.0
        draft: true

    # download the artifact that was built in the `build` job in this workflow
    - name: Download artifact hello-world
      uses: actions/download-artifact@v2.0.7
      with:
        name: hello-world
        path: hello-world/

    # upload the build artifact as a draft release asset
    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # use the upload URL from the step that created a release
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./hello-world/cpp
        asset_name: hello-world
        asset_content_type: application/octet-stream
