name: Build ./cpp

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make ./cpp
      uses: ./.github/workflows/debian-build

    - name: test ./cpp
      run: ./cpp

    - name: Create a release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: v1.0.0
        draft: true

    - name: Upload ./cpp artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: hello-world
        path: ./cpp
