#
# This is a dummy workflow, which is required because GitHub can
# only run workflows in branches if there is one with the same
# name in `main`.
#
name: Hello World 2.8.1

on: workflow_dispatch
  
jobs:
  dummy-job:
    runs-on: ubuntu-20.04
    steps:
    - run: echo done
