name: run nuget

env:
  VERSION: 1.1.0
  BUILD_NUMBER: ${{ github.run_number }}

on: workflow_dispatch

jobs:
  build:
    name: Build 
    runs-on: windows-2019
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: run tools
      shell: cmd
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall x64"
        dir /s /b "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\"
        nmake /?
        cl /?
        link /?
        nuget /?
