name: run nuget

env:
  VERSION: 1.1.0
  BUILD_NUMBER: ${{ github.run_number }}

on: workflow_dispatch

jobs:
  build:
    name: Build 
    runs-on: windows-2019
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: run tools
      run: |
        nmake /?
        cl /?
        link /?
        nuget /?
