name: Windows Build

env:
  VERSION: 1.1.0
  BUILD_NUMBER: ${{ github.run_number }}

on: workflow_dispatch

jobs:
  build:
    name: Build 
    runs-on: windows-2019
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: run tools
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall" x64
        cl /c /DBUILD_NUMBER=${{ env.BUILD_NUMBER }} test.cpp
        link /OUT:cpp.exe /SUBSYSTEM:CONSOLE test.obj
        
    - name: run cpp
      shell: cmd
      run: cpp
      
    - name: test Docker
      shell: cmd
      run: docker run --rm windows/nanoserver:1809 "cmd /C 'C:\Program Files (x86)'"
